/*
 * TeleopThread.cpp
 *
 *  Created on: 20 oct. 2016
 *      Author: wix
 */

#include "TeleopThread.h"
#include "Robot2017.h"

namespace ard
{

  TeleopThread::TeleopThread ()
  {
  }

  void
  TeleopThread::init ()
  {
    //create the thread
    g_ArdOs.createThread_Cpp("Teleop", *this, STACK_LOG, PRIO_LOG);
  }

  void
  TeleopThread::run ()
  {
    while (1)
      {
	while (Serial.available ())
	  {
	    char cmd = Serial.read ();
        
        switch (cmd)
        {
            case 's':
                g_ArdOs.displayStats();
                break;
            
            case 'p':
                ROBOT.fakeStart(RISING_EDGE);
                break;
            
            case 'g':
                ROBOT.fakeStart(FALLING_EDGE);
                break;
            
            default:
                //nothing done for now as pollution is generated by end of line characters
                //LOG(ERROR, "Teleop cmd " + String(cmd) + " unknown.");
                break;
        }
	}

      vTaskDelay(1);
    }
}

}
/* namespace ard */
