# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommonMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Types_pb2 as Types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CommonMsg.proto',
  package='apb',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x43ommonMsg.proto\x12\x03\x61pb\x1a\x0bTypes.proto\"\n\n\x08\x45mptyMsg\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\"+\n\x08PointCap\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01h\x18\x03 \x02(\x02\"\xa0\x01\n\x08NavState\x12\x19\n\x05state\x18\n \x02(\x0e\x32\n.eNavState\x12\x19\n\x05order\x18\x0b \x02(\x0e\x32\n.eNavOrder\x12\x1a\n\x03pos\x18\x0c \x02(\x0b\x32\r.apb.PointCap\x12\x0f\n\x07omronFL\x18\x15 \x02(\x08\x12\x0f\n\x07omronFR\x18\x16 \x02(\x08\x12\x0f\n\x07omronRL\x18\x17 \x02(\x08\x12\x0f\n\x07omronRR\x18\x18 \x02(\x08\">\n\x10\x43olorSensorState\x12\t\n\x01r\x18\x01 \x02(\r\x12\t\n\x01g\x18\x02 \x02(\r\x12\t\n\x01\x62\x18\x03 \x02(\r\x12\t\n\x01l\x18\x04 \x02(\r\"<\n\x0e\x41\x63tuatorsState\x12*\n\x0b\x63olorSensor\x18\x01 \x02(\x0b\x32\x15.apb.ColorSensorState')
  ,
  dependencies=[Types__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EMPTYMSG = _descriptor.Descriptor(
  name='EmptyMsg',
  full_name='apb.EmptyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=47,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='apb.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='apb.Point.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='apb.Point.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=78,
)


_POINTCAP = _descriptor.Descriptor(
  name='PointCap',
  full_name='apb.PointCap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='apb.PointCap.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='apb.PointCap.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='h', full_name='apb.PointCap.h', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=123,
)


_NAVSTATE = _descriptor.Descriptor(
  name='NavState',
  full_name='apb.NavState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='apb.NavState.state', index=0,
      number=10, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='order', full_name='apb.NavState.order', index=1,
      number=11, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='apb.NavState.pos', index=2,
      number=12, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='omronFL', full_name='apb.NavState.omronFL', index=3,
      number=21, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='omronFR', full_name='apb.NavState.omronFR', index=4,
      number=22, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='omronRL', full_name='apb.NavState.omronRL', index=5,
      number=23, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='omronRR', full_name='apb.NavState.omronRR', index=6,
      number=24, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=286,
)


_COLORSENSORSTATE = _descriptor.Descriptor(
  name='ColorSensorState',
  full_name='apb.ColorSensorState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='apb.ColorSensorState.r', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g', full_name='apb.ColorSensorState.g', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='apb.ColorSensorState.b', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l', full_name='apb.ColorSensorState.l', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=350,
)


_ACTUATORSSTATE = _descriptor.Descriptor(
  name='ActuatorsState',
  full_name='apb.ActuatorsState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='colorSensor', full_name='apb.ActuatorsState.colorSensor', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=412,
)

_NAVSTATE.fields_by_name['state'].enum_type = Types__pb2._ENAVSTATE
_NAVSTATE.fields_by_name['order'].enum_type = Types__pb2._ENAVORDER
_NAVSTATE.fields_by_name['pos'].message_type = _POINTCAP
_ACTUATORSSTATE.fields_by_name['colorSensor'].message_type = _COLORSENSORSTATE
DESCRIPTOR.message_types_by_name['EmptyMsg'] = _EMPTYMSG
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['PointCap'] = _POINTCAP
DESCRIPTOR.message_types_by_name['NavState'] = _NAVSTATE
DESCRIPTOR.message_types_by_name['ColorSensorState'] = _COLORSENSORSTATE
DESCRIPTOR.message_types_by_name['ActuatorsState'] = _ACTUATORSSTATE

EmptyMsg = _reflection.GeneratedProtocolMessageType('EmptyMsg', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYMSG,
  __module__ = 'CommonMsg_pb2'
  # @@protoc_insertion_point(class_scope:apb.EmptyMsg)
  ))
_sym_db.RegisterMessage(EmptyMsg)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'CommonMsg_pb2'
  # @@protoc_insertion_point(class_scope:apb.Point)
  ))
_sym_db.RegisterMessage(Point)

PointCap = _reflection.GeneratedProtocolMessageType('PointCap', (_message.Message,), dict(
  DESCRIPTOR = _POINTCAP,
  __module__ = 'CommonMsg_pb2'
  # @@protoc_insertion_point(class_scope:apb.PointCap)
  ))
_sym_db.RegisterMessage(PointCap)

NavState = _reflection.GeneratedProtocolMessageType('NavState', (_message.Message,), dict(
  DESCRIPTOR = _NAVSTATE,
  __module__ = 'CommonMsg_pb2'
  # @@protoc_insertion_point(class_scope:apb.NavState)
  ))
_sym_db.RegisterMessage(NavState)

ColorSensorState = _reflection.GeneratedProtocolMessageType('ColorSensorState', (_message.Message,), dict(
  DESCRIPTOR = _COLORSENSORSTATE,
  __module__ = 'CommonMsg_pb2'
  # @@protoc_insertion_point(class_scope:apb.ColorSensorState)
  ))
_sym_db.RegisterMessage(ColorSensorState)

ActuatorsState = _reflection.GeneratedProtocolMessageType('ActuatorsState', (_message.Message,), dict(
  DESCRIPTOR = _ACTUATORSSTATE,
  __module__ = 'CommonMsg_pb2'
  # @@protoc_insertion_point(class_scope:apb.ActuatorsState)
  ))
_sym_db.RegisterMessage(ActuatorsState)


# @@protoc_insertion_point(module_scope)
