/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Tue Jan 17 02:54:31 2017. */

#include "Types.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif




/* @@protoc_insertion_point(eof) */
