/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Tue Jan 17 02:54:31 2017. */

#ifndef PB_TYPES_PB_H_INCLUDED
#define PB_TYPES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _eDir {
    eDir_UNDEFINED = 0,
    eDir_FORWARD = 1,
    eDir_BACKWARD = -1
} eDir;
#define _eDir_MIN eDir_UNDEFINED
#define _eDir_MAX eDir_BACKWARD
#define _eDir_ARRAYSIZE ((eDir)(eDir_BACKWARD+1))

typedef enum _eColor {
    eColor_UNKNOWN = 0,
    eColor_PREF = 1,
    eColor_SYM = 2
} eColor;
#define _eColor_MIN eColor_UNKNOWN
#define _eColor_MAX eColor_SYM
#define _eColor_ARRAYSIZE ((eColor)(eColor_SYM+1))

typedef enum _eNavState {
    eNavState_IDLE = 0,
    eNavState_FACING_DEST = 1,
    eNavState_GOING_TO_TARGET = 2,
    eNavState_TURNING_AT_TARGET = 3,
    eNavState_STOPPING = 4
} eNavState;
#define _eNavState_MIN eNavState_IDLE
#define _eNavState_MAX eNavState_STOPPING
#define _eNavState_ARRAYSIZE ((eNavState)(eNavState_STOPPING+1))

typedef enum _eNavOrder {
    eNavOrder_NOTHING = 0,
    eNavOrder_GOTO = 1,
    eNavOrder_GOTO_CAP = 2,
    eNavOrder_STOP = 3
} eNavOrder;
#define _eNavOrder_MIN eNavOrder_NOTHING
#define _eNavOrder_MAX eNavOrder_STOP
#define _eNavOrder_ARRAYSIZE ((eNavOrder)(eNavOrder_STOP+1))

typedef enum _eLogLevel {
    eLogLevel_DEBUG = 0,
    eLogLevel_INFO = 1,
    eLogLevel_ERROR = 2,
    eLogLevel_ASSERT = 3
} eLogLevel;
#define _eLogLevel_MIN eLogLevel_DEBUG
#define _eLogLevel_MAX eLogLevel_ASSERT
#define _eLogLevel_ARRAYSIZE ((eLogLevel)(eLogLevel_ASSERT+1))

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
